list(APPEND PROJECT_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/mainwindow.h
    ${CMAKE_CURRENT_LIST_DIR}/mainwindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mainwindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/cardtableitemmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/cardtableitemmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cardtablesortfiltermodel.h
    ${CMAKE_CURRENT_LIST_DIR}/cardtablesortfiltermodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fieldtableitemmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/fieldtableitemmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fieldtablesortfiltermodel.h
    ${CMAKE_CURRENT_LIST_DIR}/fieldtablesortfiltermodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aboutdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/aboutdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aboutdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/cardeditdialog.h
    ${CMAKE_CURRENT_LIST_DIR}/cardeditdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cardeditdialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/editfieldlistmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/editfieldlistmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/translations.h
    ${CMAKE_CURRENT_LIST_DIR}/translations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fieldvalueeditdelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/fieldvalueeditdelegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/newcarddialog.h
    ${CMAKE_CURRENT_LIST_DIR}/newcarddialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/newcarddialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/newnotedialog.h
    ${CMAKE_CURRENT_LIST_DIR}/newnotedialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/newnotedialog.ui
    ${CMAKE_CURRENT_LIST_DIR}/passworddialog.h
    ${CMAKE_CURRENT_LIST_DIR}/passworddialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passworddialog.ui
)
